stages:
  - build
  - apk-firebase-app-distribution

build:
  stage: build
  script:
    - echo "Building the application"
    - flutter clean && flutter pub get

apk-firebase-app-distribution:
  stage: apk-firebase-app-distribution
  script:
    - echo "Building the APK"
    - build_name="$(cut -d'/' -f2 <<<"$CI_COMMIT_TAG")"
    - echo $build_name
    - build_number="$(cut -d'/' -f3 <<<"$CI_COMMIT_TAG")"
    - echo $build_number
    - flutter build apk --release --build-name=$build_name --build-number=$build_number
    - echo "Uploading the APK to Firebase App Distribution"
    - firebase appdistribution:distribute build/app/outputs/flutter-apk/app-staging-release.apk --app 1:211127426949:android:25da9cfa382b6505faaeec --groups "mee"
