name: ihun_jobfindie
description: "An app for job seekers to find their dream job. Using Flutter. Powered by Own built API."

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## UI
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  cached_network_image: ^3.3.0
  flutter_vector_icons: ^2.0.0

  ## State Management & Navigation & Network
  fpdart: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  timeago: ^3.5.0
  http: ^1.1.0
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  get: ^4.6.6

  ## Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_json/
    - assets/icons/
