name: ihun_jobfindie
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  cached_network_image: ^3.2.3

  equatable: ^2.0.5
  flutter_vector_icons: ^2.0.0
  flutter_zoom_drawer: ^3.1.1
  fpdart: ^1.1.0
  dio: ^5.3.2
  flutter_riverpod: ^2.3.10
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  go_router: ^10.1.2
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_json/
    - assets/icons/