name: ihun_jobfindie
description: "An app for job seekers to find their dream job. Using Flutter. Powered by Own built API."

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## UI
  dots_indicator: ^3.0.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0

  ## State Management & Navigation & Network
  equatable: ^2.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  http: ^1.1.0
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  get: ^4.6.6

  ## Firebase
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_storage: ^12.1.1

  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0
  flutter_toggle_tab: ^1.4.1
  lottie: ^3.1.2
  pull_to_refresh_plus: ^2.0.3
  flutter_network_connectivity: ^0.0.6
  flutter_svg: ^2.0.9
  timeago: ^3.7.0
  rxdart: ^0.27.7
  file_picker: ^8.0.6
  dotted_border: ^2.1.0
  permission_handler: ^11.3.1
  onesignal_flutter: ^5.2.2
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  url_launcher: ^6.3.0
  syncfusion_flutter_pdfviewer: ^26.2.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_json/
    - assets/icons/
    - assets/vector/
