name: Flutter App Distribution

on:
  push:
    branches:
      - main # or any branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.0' # specify the flutter version you are using

    - name: Install dependencies
      run: flutter pub get

    - name: Clean project
      run: flutter clean

    - name: Build APK
      run: flutter build apk --release --flavor staging

    - name: Distribute to Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Ensure you have set the FIREBASE_TOKEN secret in your repository
      run: |
        flutter firebase appdistribution:distribute build/app/outputs/flutter-apk/app-staging-release.apk \
          --app 1:211127426949:android:25da9cfa382b6505faaeec \
          --groups "mee"